### ISSUE TITLE
Can't authenticate

### ISSUE THREAD

**Issue by moonshaadow** [vitiko98/mopidy-qobuz#9]
Hi there, 
I have the following issue when starting `mopidy` : 
```

ERROR    2024-01-16 10:34:23,040 [8033:QobuzBackend-3 (_actor_loop)] pykka
  Unhandled exception in QobuzBackend (urn:uuid:b33adaaa-53fe-43fd-87da-b58f93b65ab6):
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 186, in _actor_loop
    self.on_start()
  File "/home/studio/.local/lib/python3.10/site-packages/mopidy_qobuz/backend.py", line 35, in on_start
    self._client.login(config["username"], config["password"])
  File "/home/studio/.local/lib/python3.10/site-packages/mopidy_qobuz/client/__init__.py", line 68, in login
    self._auth(email, password)
  File "/home/studio/.local/lib/python3.10/site-packages/mopidy_qobuz/client/__init__.py", line 81, in _auth
    raise AuthenticationError(_get_message(response))
mopidy_qobuz.client.AuthenticationError: Invalid username/email and password combination
ERROR    2024-01-16 10:34:23,040 [8033:MainThread] mopidy.commands
  Actor died: QobuzBackend (urn:uuid:b33adaaa-53fe-43fd-87da-b58f93b65ab6) stopped before handling the message
```

I have a valid account, my user name is like XXX.XXX@XXX.XX and my password has numbers and uppercase letters.

**Comment by moonshaadow** [comment]
Sorry, it's an stupid typo.

I close.
